<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY4IIQYF\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY4IIQYF/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerY4IIQYF.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerY4IIQYF\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerY4IIQYF\App_KernelProdContainer([
    'container.build_hash' => 'Y4IIQYF',
    'container.build_id' => '3a851454',
    'container.build_time' => 1756882791,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY4IIQYF');
